#
# Configuration file

general:
  max_days_stored: 5
  db: sqlite://db/arxiv-sieve.sqlite3

user:
  categories: math.DG, math.MG, math.AT, math.GT, q-bio.QM
  keywords: interesting, things, in, differential, geometry
  order_by: nothing # subject, name, authors
  ignore_updates: false
  email:

smtp:
  server:
  port:
  host:
  from:
  password:
